apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: bentley
resources:
- ../../k8s
- app/route-api.yaml
patches:
- path: app/deployment.yaml
  target:
    kind: Deployment
    name: app
    version: v1
- path: app/route-staff.yaml
  target:
    kind: Route
    name: aspace-staff
    version: v1
secretGenerator:
- name: app-secret
  envs:
  - app/.env.deployment.bentley
