apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: clements
resources:
- ../../base-with-cert
patches:
- path: app/deployment.yaml
  target:
    kind: Deployment
    name: app
    version: v1
- path: app/route-staff.yaml
  target:
    kind: Route
    name: aspace-staff
    version: v1
- path: app/cert.yaml
  target:
    kind: Certificate
    name: aspace
    version: v1
secretGenerator:
- name: app-secret
  envs:
  - app/.env.deployment.clements
