AppConfig[:db_url] = "$APPCONFIG_DB_URL"
AppConfig[:solr_url] = "$APPCONFIG_SOLR_URL"

AppConfig[:backend_url] = "$APPCONFIG_HOST_URL:8089"
AppConfig[:frontend_url] = "$APPCONFIG_HOST_URL:8080"
AppConfig[:public_url] = "$APPCONFIG_HOST_URL:8081"
AppConfig[:oai_url] = "$APPCONFIG_HOST_URL:8082"
AppConfig[:indexer_url] = "$APPCONFIG_HOST_URL:8091"
AppConfig[:docs_url] = "$APPCONFIG_HOST_URL:8888"

AppConfig[:frontend_log] = "/archivesspace/logs/archivesspace.out"
AppConfig[:frontend_log_level] = "warn"
AppConfig[:backend_log] = "/archivesspace/logs/archivesspace.out"
AppConfig[:backend_log_level] = "warn"
AppConfig[:pui_log] = "/archivesspace/logs/archivesspace.out"
AppConfig[:pui_log_level] = "info"
AppConfig[:indexer_log] = "/archivesspace/logs/archivesspace.out"
AppConfig[:indexer_log_level] = "info"
