---
name: aspace
services:
  app:
    depends_on:
      - solr
      - db
    image: aspace-app
    build:
      context: ./app
    env_file:
      - ./app/.env
    volumes:
      - app-data:/archivesspace/data
      - app-logs:/archivesspace/logs
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
      - "8888:8888"
  clements:
    depends_on:
      - db
      - solr
    build:
      context: ./app
      dockerfile: instances/clements/Dockerfile.clements
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    volumes:
      - app-data:/archivesspace/data
      - app-logs:/archivesspace/logs
  scrc:
    depends_on:
      - db
      - solr
    build:
      context: ./app
      dockerfile: instances/scrc/Dockerfile.scrc
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    volumes:
      - app-data:/archivesspace/data
      - app-logs:/archivesspace/logs
  bentley:
    depends_on:
      - db
      - solr
    build:
      context: ./app
      dockerfile: instances/bentley/Dockerfile.bentley
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    volumes:
      - app-data:/archivesspace/data
      - app-logs:/archivesspace/logs
  db:
    image: mysql:8
    env_file:
      - ./db/.env
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--log_bin_trust_function_creators=1'
    ]
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  solr:
    image: aspace-solr
    build:
      context: ./solr
    volumes:
      - solr-data:/var/solr
    ports:
      - "8983:8983"
volumes:
  app-data:
  app-logs:
  db-data:
  solr-data:
