---
services:

  app:
    depends_on:
      - db
      - solr
    image: aspace-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
      - "8888:8888"
    volumes:
      - app-data:/archivesspace/data
      - app-logs:/archivesspace/logs
#    command: sleep infinity

  db:
    image: bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=archivesspace
      - MARIADB_USER=as
      - MARIADB_PASSWORD=as123
      - TZ=America/Detroit
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  solr:
    image: aspace-solr
    build:
      dockerfile: Dockerfile
      context: ./solr
    environment:
      - SOLR_JAVA_MEM=-Xms1024m -Xmx1024m
      - SOLR_HEAP=1024m
    volumes:
      - solr-data:/var/solr
    ports:
      - "8983:8983"

volumes:

  app-data:
  app-logs:
  db-data:
  solr-data:
