# frozen_string_literal: true

ArchivesSpace::Application.routes.draw do
  scope AppConfig[:frontend_proxy_prefix] do

    # Generated by Omniauth
    # /auth/:provider

    get '/auth/:provider/callback', to: 'oidc#create'
    post '/auth/:provider/callback', to: 'oidc#create'
    get '/auth/failure', to: 'oidc#failure'
    get '/auth/logout', to: 'oidc#logout'
  end
end
