---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: aspace
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: aspace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: aspace
    spec:
      containers:
        - image: ghcr.io/mlibrary/aspace-containerization/aspace-app:v3.3.1
          name: app
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
            - name: SOLR_URL
              value: "http://solr:8983/solr/archivesspace"
            - name: HOST_URL
              value: "http://aspace"
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8089
            - containerPort: 8090
            - containerPort: 8091
            - containerPort: 8888
          volumeMounts:
            - name: app-data
              mountPath: /archivesspace/data
            - name: app-logs
              mountPath: /archivesspace/logs
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: aspace
  name: aspace
spec:
  ports:
    - name: "staff"
      targetPort: 8080
      port: 8080
    - name: "public"
      targetPort: 8081
      port: 8081
    - name: "backend"
      targetPort: 8089
      port: 8089
  selector:
    service: aspace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: aspace
  name: app-data
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: aspace
  name: app-logs
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: solr
    spec:
      containers:
        - image: ghcr.io/mlibrary/aspace-containerization/aspace-solr:v3.3.1
          name: solr
          imagePullPolicy: IfNotPresent
          env:
            - name: SOLR_JAVA_MEM
              value: "-Xms1024m -Xmx1024m"
            - name: SOLR_HEAP
              value: "1024m"
          ports:
            - containerPort: 8983
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: solr
  name: solr
spec:
  ports:
    - name: "solr"
      targetPort: 8983
      port: 8983
  selector:
    service: solr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: solr
  name: solr-data
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
