apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- app/cert.yaml
patches:
- path: app/route-staff.yaml
  target:
    kind: Route
    name: aspace-staff
    version: v1
