ASpaceGems.setup if defined? ASpaceGems
source 'https://rubygems.org'

# Seem to need this specified?
gem 'rails', '5.2.5'
gem 'omniauth', '~>2.1'
gem 'omniauth_openid_connect', '>=0.4'
gem 'omniauth-rails_csrf_protection'

# Pinning these to prevent problems?
gem 'public_suffix', '4.0.6'
gem 'addressable', '2.8.0'
gem 'json-jwt', '1.13.0'
gem 'openid_connect', '1.3.0'
