apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  url: jdbc:mysql://wps-cs-mariadb-01.aws.vdc.it.umich.edu:3306/archivesspace?user=archivesspace&password=<archivesspace_password>&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
