FROM aspace-app

COPY instances/bentley/bentley_config.rb /archivesspace/config/bentley_config.rb
RUN cat /archivesspace/config/bentley_config.rb >> /archivesspace/config/config.rb

ENV PLUGINS="lcnaf"
