apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: aspace
  name: app-data
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
