ARG ASPACE_APP_IMAGE=aspace-app
FROM $ASPACE_APP_IMAGE

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
        patch && \
    rm -rf /var/lib/apt/lists/*

RUN cd /archivesspace/plugins && \
    git clone --depth 1 --branch v1.0 https://github.com/hudmol/extended_advanced_search.git && \
    git clone --depth 1 https://github.com/mlibrary/aspace-clements-customization.git

RUN patch /archivesspace/locales/en.yml /archivesspace/plugins/aspace-clements-customization/en.yml.diff

COPY instances/clements/clements_config.rb /archivesspace/config/clements_config.rb
RUN cat /archivesspace/config/clements_config.rb >> /archivesspace/config/config.rb

ENV PLUGINS="aspace-clements-customization,extended_advanced_search"
