apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app/deployment.yml
- app/route-staff.yml
- app/service.yml
- app/volume-data.yml
- app/volume-logs.yml
- solr/deployment.yml
- solr/service.yml
- solr/volume.yml
