apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: solr
  name: solr-data
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
