ARG ASPACE_APP_IMAGE=aspace-app
FROM $ASPACE_APP_IMAGE

RUN cd /archivesspace/plugins && \
    git clone https://github.com/bentley-historical-library/accession_events.git && \
    git clone https://github.com/bentley-historical-library/aspace-jsonmodel-from-format.git && \
    git clone https://github.com/bentley-historical-library/bhl_accession_search.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_accessrestrict_text.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_branding.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_print_template.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_translations.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_reports.git && \
    git clone https://github.com/bentley-historical-library/bhl_barcode.git && \
    git clone https://github.com/bentley-historical-library/bhl-ead-importer.git && \
    git clone https://github.com/bentley-historical-library/bulk_create_containers.git && \
    git clone https://github.com/bentley-historical-library/donor_details.git && \
    git clone https://github.com/bentley-historical-library/generate_bhl_identifiers.git && \
    git clone https://github.com/bentley-historical-library/timewalk.git && \
    git clone https://github.com/bentley-historical-library/user_defined_in_basic.git && \
    git clone https://github.com/bentley-historical-library/aspace_tree_endpoint.git && \
    rm -rf refid_rules && git clone https://github.com/bentley-historical-library/refid_rules.git && \
    git clone https://github.com/bentley-historical-library/bhl_aspace_export.git && \
    git clone https://github.com/lyrasis/aspace-reindexer.git && \
    git clone https://github.com/hudmol/as_history.git

RUN /archivesspace/scripts/initialize-plugin.sh timewalk

COPY instances/bentley/bentley_config.rb /archivesspace/config/bentley_config.rb
RUN cat /archivesspace/config/bentley_config.rb >> /archivesspace/config/config.rb

ENV PLUGINS accession_events,aspace-jsonmodel-from-format,\
    bhl_accession_search,bhl_aspace_accessrestrict_text,bhl_aspace_branding,\
    bhl_aspace_print_template,bhl_aspace_translations,\
    bhl_aspace_reports,bhl_barcode,bhl-ead-importer,\
    bulk_create_containers,donor_details,generate_bhl_identifiers,timewalk,\
    user_defined_in_basic,aspace_tree_endpoint,refid_rules,\
    bhl_aspace_export,aspace-reindexer,as_history
