---
name: "Build db image"

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
    inputs:
      archives_space_version:
        description: "Archives Space Version"
        required: true
        default: "latest"
        type: choice
        options:
          - "latest"
          - "v3.3.1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./db
          push: true
          tags: 'ghcr.io/mlibrary/aspace-containerization/aspace-db:${{ github.sha }}, ghcr.io/mlibrary/aspace-containerization/aspace-db:${{ github.event.inputs.archives_space_version }}'
          file: ./db/Dockerfile
          build-args: |
            ASPACE_VERSION=${{ github.event.inputs.archives_space_version }}
