---
name: "Build spcoll image"

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: 'ghcr.io/mlibrary/aspace-containerization/aspace-spcoll:${{ github.sha }}, ghcr.io/mlibrary/aspace-containerization/aspace-spcoll:latest'
          file: ./app/instances/spcoll/Dockerfile.spcoll
          build-args: |
            ASPACE_IMAGE_NAME=ghcr.io/mlibrary/aspace-containerization/aspace-app:3.3.1
